### ISSUE TITLE
Bug in ansible galaxy replaced '-' with '_' in role name

### ISSUE THREAD

**Issue by spk83** [andrewrothstein/ansible-alpine-glibc-shim#1]
Just for info - noticed an issue with ansible galaxy - https://github.com/ansible/galaxy/issues/775 

They have published your roles after replacing '-' with '_'  in your role names after your last import there. Noticed the same with ansible-java-oracle role. 😓

**Comment by johnfriz** [comment]
Seeing the same thing and it's breaking https://galaxy.ansible.com/andrewrothstein/openshift-origin-client-tools

**Comment by andrewrothstein** [comment]
this was nonsense with the galaxy. should be fixed now.
